language: php

sudo: false

env:
    global:
        - COMPOSER_LOWEST=""

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: COMPOSER_LOWEST=""
        - php: 5.6
          env: COMPOSER_LOWEST="--prefer-lowest"
    fast_finish: true

before_install:
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer self-update
    - composer install
    - composer update symfony/framework-bundle $COMPOSER_LOWEST

script:
  - phpunit --exclude-group=none

branches:
  only:
      - master
      - develop

services:
    - mongodb
    - elasticsearch
